### ISSUE TITLE
publish token fails

### ISSUE THREAD

**Issue by nolash** [grassrootseconomics/sarafu.network#131] opened 2024-06-11 13:56 UTC
tried add LASH token with wallet 0x9E24675E81126f6fbC8eBf8DB7Cb22869D160696

error message popup telling (paraphrase) "failed add to graph"

**Comment by WillRuddick** [comment] 2024-07-22 13:28
couldn't reproduce.
Was this through a browser? What wallet?

**Comment by nolash** [comment] 2024-07-23 13:07
yes browser, cant remember wallet but probably metamask, possibly brave wallet.

**Comment by williamluke4** [comment] 2024-08-15 08:44
This should be fixed.

**Comment by nolash** [comment] 2024-08-23 22:41
still fails

**Comment by williamluke4** [comment] 2024-08-25 04:13
This failed for a different error and is fixed

**Closed** 2024-08-25 04:13 UTC
